/* ============================================================
   TEACHER HQ — BLOOM VERB REFERENCE
   Source: user-provided Bloom's Taxonomy action-word table.
   This is a suggestion aid only; teacher overrides always win.
============================================================ */

window.TEACHER_HQ_BLOOM = {
  "levels": {
    "Remember": [
      "copy",
      "define",
      "describe",
      "discover",
      "duplicate",
      "enumerate",
      "examine",
      "identify",
      "label",
      "list",
      "listen",
      "locate",
      "match",
      "memorize",
      "name",
      "observe",
      "omit",
      "quote",
      "read",
      "recall",
      "recite",
      "recognize",
      "record",
      "repeat",
      "reproduce",
      "retell",
      "select",
      "state",
      "tabulate",
      "tell",
      "visualize"
    ],
    "Understand": [
      "ask",
      "associate",
      "cite",
      "classify",
      "compare",
      "contrast",
      "convert",
      "demonstrate",
      "describe",
      "differentiate",
      "discover",
      "discuss",
      "distinguish",
      "estimate",
      "explain",
      "express",
      "extend",
      "generalize",
      "give examples",
      "group",
      "identify",
      "illustrate",
      "indicate",
      "infer",
      "interpret",
      "judge",
      "observe",
      "order",
      "paraphrase",
      "predict",
      "relate",
      "report",
      "represent",
      "research",
      "restate",
      "review",
      "rewrite",
      "select",
      "show",
      "summarize",
      "trace",
      "transform",
      "translate"
    ],
    "Apply": [
      "act",
      "administer",
      "apply",
      "articulate",
      "calculate",
      "change",
      "chart",
      "choose",
      "collect",
      "complete compute",
      "construct",
      "demonstrate",
      "determine",
      "develop",
      "discover",
      "dramatize",
      "employ",
      "establish",
      "examine",
      "experiment",
      "explain",
      "illustrate",
      "interpret",
      "interview",
      "judge",
      "list",
      "manipulate",
      "modify",
      "operate",
      "paint",
      "practice",
      "predict",
      "prepare",
      "produce",
      "record",
      "relate",
      "report",
      "schedule",
      "show",
      "simulate",
      "sketch",
      "teach",
      "transfer",
      "use",
      "write"
    ],
    "Analyze": [
      "advertise",
      "analyze",
      "appraise",
      "break down",
      "calculate",
      "categorize",
      "classify",
      "compare",
      "conclude",
      "connect",
      "contrast",
      "correlate",
      "criticize",
      "deduce",
      "devise",
      "diagram",
      "differentiate",
      "discriminate",
      "dissect",
      "distinguish",
      "divide",
      "estimate",
      "evaluate",
      "experiment",
      "explain",
      "focus",
      "illustrate",
      "infer",
      "order",
      "organize",
      "outline",
      "plan",
      "point out",
      "prioritize",
      "question",
      "select",
      "separate",
      "subdivide",
      "survey",
      "test"
    ],
    "Evaluate": [
      "appraise",
      "argue",
      "assess",
      "choose",
      "compare",
      "conclude",
      "consider",
      "convince",
      "criticize",
      "critique",
      "debate",
      "decide",
      "defend",
      "discriminate",
      "distinguish",
      "editorialize",
      "estimate",
      "evaluate",
      "find errors",
      "grade",
      "judge",
      "justify",
      "measure",
      "order",
      "persuade",
      "predict",
      "rank",
      "rate",
      "recommend",
      "reframe",
      "score",
      "select",
      "summarize",
      "support",
      "test",
      "weigh"
    ],
    "Create": [
      "adapt",
      "anticipate",
      "arrange",
      "assemble",
      "choose",
      "collaborate",
      "collect",
      "combine",
      "compile",
      "compose",
      "construct",
      "create",
      "design",
      "develop",
      "devise",
      "express",
      "facilitate",
      "formulate",
      "generalize",
      "hypothesize",
      "imagine",
      "infer",
      "integrate",
      "intervene",
      "invent",
      "justify",
      "make",
      "manage",
      "modify",
      "negotiate",
      "organize",
      "originate",
      "plan",
      "prepare",
      "produce",
      "propose",
      "rearrange",
      "reorganize",
      "report",
      "revise",
      "rewrite",
      "role-play",
      "substitute",
      "schematize",
      "simulate",
      "solve",
      "speculate",
      "structure",
      "support",
      "test",
      "validate",
      "write"
    ]
  },
  "preferred": {
    "describe": "Understand",
    "discover": "Understand",
    "examine": "Apply",
    "identify": "Remember",
    "select": "Remember",
    "classify": "Analyze",
    "compare": "Analyze",
    "demonstrate": "Apply",
    "differentiate": "Analyze",
    "distinguish": "Analyze",
    "estimate": "Apply",
    "explain": "Understand",
    "illustrate": "Apply",
    "interpret": "Understand",
    "judge": "Evaluate",
    "order": "Understand",
    "predict": "Apply",
    "relate": "Understand",
    "report": "Understand",
    "represent": "Understand",
    "show": "Apply",
    "summarize": "Understand",
    "calculate": "Apply",
    "choose": "Apply",
    "collect": "Apply",
    "create": "Create",
    "determine": "Apply",
    "develop": "Apply",
    "evaluate": "Evaluate",
    "experiment": "Analyze",
    "organize": "Analyze",
    "plan": "Analyze",
    "test": "Analyze",
    "appraise": "Evaluate",
    "support": "Evaluate",
    "write": "Create",
    "express": "Understand",
    "recognize": "Remember",
    "apply": "Apply",
    "assess": "Evaluate",
    "solve": "Create",
    "investigate": "Analyze"
  }
};
