/* ============================================================
   TEACHER HQ — FULL CALENDAR PAGE
   ------------------------------------------------------------
   This page intentionally reads the same local Teacher HQ data as the
   main application but does NOT load app.js. Keeping it self-contained
   prevents the large dashboard script from depending on DOM nodes that do
   not exist on calendar.html.
============================================================ */
(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  let state=null,user=null,visible=new Date(),classFilter="";
  const WEEKDAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];

  function escapeHTML(v){return String(v??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));}
  function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
  function parseDate(key){const [y,m,d]=String(key).split("-").map(Number);return new Date(y,m-1,d);}
  function fmtDate(key){if(!key)return"";return parseDate(key).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});}
  function fmtLong(key){if(!key)return"";return parseDate(key).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"});}
  function fmtTime(value){if(!value)return"";const [h,m]=value.split(":").map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"});}
  function classKey(spec){return `${[...(spec?.grades||[])].sort().join("|")}::${String(spec?.subject||"").trim().toLowerCase()}`;}
  function classLabel(spec){const grades=spec?.grades||[];const gl=grades.length===1?grades[0]:grades.length?`Grade ${grades.map(g=>g.replace(/^Grade\s+/i,"").replace("Kindergarten","K")).join("/")}`:"";return `${gl} ${spec?.subject||""}`.trim();}
  function duration(a,b){const [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number);return bh*60+bm-(ah*60+am);}
  function contrast(hex){const h=String(hex||"").replace("#","");if(!/^[0-9a-f]{6}$/i.test(h))return"#17171a";const r=parseInt(h.slice(0,2),16)/255,g=parseInt(h.slice(2,4),16)/255,b=parseInt(h.slice(4),16)/255;const cv=x=>x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4);return .2126*cv(r)+.7152*cv(g)+.0722*cv(b)>.48?"#17171a":"#fff";}

  function load(){
    const keys=Object.keys(localStorage).filter(k=>/^teacherHQData_v\d+$/.test(k)).sort((a,b)=>Number(b.match(/\d+$/)[0])-Number(a.match(/\d+$/)[0]));
    for(const key of keys){try{const parsed=JSON.parse(localStorage.getItem(key));if(parsed?.users){state=parsed;break;}}catch{}}
    if(!state)return;
    const active=state.activeUserId||localStorage.getItem("teacherHQActiveUserId");user=state.users.find(u=>u.id===active)||state.users[0]||null;
  }

  function exceptionFor(key){return (user?.calendarExceptions||[]).find(item=>key>=(item.startDate||item.date||"")&&key<=(item.endDate||item.startDate||item.date||""));}
  function termsFor(key){return (user?.terms||[]).filter(term=>key>=term.startDate&&key<=term.endDate);}
  function versionFor(term,key){return (term.scheduleVersions||[]).filter(v=>key>=v.effectiveStart&&key<=v.effectiveEnd).sort((a,b)=>a.effectiveStart.localeCompare(b.effectiveStart)).at(-1);}
  function occurrences(key){if(exceptionFor(key))return[];const date=parseDate(key),weekday=WEEKDAYS[date.getDay()],rows=[];termsFor(key).forEach(term=>{const version=versionFor(term,key);(version?.scheduleBlocks||[]).filter(b=>b.weekday===weekday).forEach(block=>rows.push({term,version,block,dateKey:key,planned:block.blockType==="Instructional Time"&&(block.plannedDates||[]).includes(key)}));});return rows.sort((a,b)=>a.block.startTime.localeCompare(b.block.startTime));}
  function units(){return user?.units||[];}
  function lessonsOn(key){return units().flatMap(unit=>(unit.lessons||[]).filter(lesson=>lesson.dateKey===key).map(lesson=>({unit,lesson})));}
  function tripsOn(key){return units().flatMap(unit=>(unit.workspace?.fieldTrips||[]).filter(t=>key>=t.startDate&&key<=t.endDate).map(trip=>({unit,trip})));}
  function assessmentsOn(key){return units().flatMap(unit=>(unit.workspace?.assessments||[]).filter(a=>a.status!=="draft"&&a.date===key).map(assessment=>({unit,assessment})));}
  function matchingClass(spec){return !classFilter||classKey(spec)===classFilter;}
  function teachingClass(spec){return (user?.classes||[]).find(c=>classKey({grades:c.grades,subject:c.subject})===classKey(spec));}
  function courseColour(spec){return teachingClass(spec)?.colour||"#61B6FF";}
  function lessonTitle(lesson){return lesson.customTitle?`${lesson.sequence} - ${lesson.customTitle}`:`Lesson ${lesson.sequence}`;}
  function lessonForOccurrence(occ){const key=`${occ.term.id}|${occ.version.id}|${occ.block.id}|${occ.dateKey}`;return lessonsOn(occ.dateKey).find(({lesson})=>`${lesson.termId}|${lesson.versionId}|${lesson.blockId}|${lesson.dateKey}`===key);}

  function renderClasses(){const select=$("fullCalendarClassFilter");(user?.classes||[]).forEach(c=>select.insertAdjacentHTML("beforeend",`<option value="${escapeHTML(classKey({grades:c.grades,subject:c.subject}))}">${escapeHTML(c.name)}</option>`));select.onchange=()=>{classFilter=select.value;render();};}

  function render(){if(!user)return;$("fullCalendarMonth").textContent=visible.toLocaleDateString(undefined,{month:"long",year:"numeric"});const grid=$("fullCalendarGrid");grid.innerHTML="";["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].forEach((d,i)=>grid.insertAdjacentHTML("beforeend",`<div class="full-calendar-weekday ${i===0||i===6?"weekend":""}">${d}</div>`));const y=visible.getFullYear(),m=visible.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),today=dateKey(new Date());for(let i=0;i<first;i++)grid.insertAdjacentHTML("beforeend",'<div class="full-day blank"></div>');for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,date=new Date(y,m,d),cell=document.createElement("button");cell.type="button";cell.className=`full-day ${[0,6].includes(date.getDay())?"weekend":""} ${key<today?"past":""} ${key===today?"today":""}`;cell.innerHTML=`<span class="full-day-number">${d}</span><div class="full-day-events"></div>`;const inner=cell.querySelector(".full-day-events"),off=exceptionFor(key);if(off)inner.insertAdjacentHTML("beforeend",`<span class="full-event off">${escapeHTML(off.label||off.title||off.type)}</span>`);occurrences(key).filter(o=>o.block.blockType==="Instructional Time"&&matchingClass({grades:o.block.grades,subject:o.block.subject})).forEach(o=>{const linked=lessonForOccurrence(o);if(linked){const bg=courseColour(linked.unit.classSpec);inner.insertAdjacentHTML("beforeend",`<span class="full-event lesson" style="--event-bg:${bg};--event-fg:${contrast(bg)}">${escapeHTML(lessonTitle(linked.lesson))}</span>`);}else inner.insertAdjacentHTML("beforeend",`<span class="full-event unplanned">${escapeHTML(teachingClass({grades:o.block.grades,subject:o.block.subject})?.name||classLabel({grades:o.block.grades,subject:o.block.subject}))} · needs plan</span>`);});tripsOn(key).filter(({unit})=>matchingClass(unit.classSpec)).forEach(({trip})=>inner.insertAdjacentHTML("beforeend",`<span class="full-event trip">🚌 ${escapeHTML(trip.title)}</span>`));assessmentsOn(key).filter(({unit})=>matchingClass(unit.classSpec)).forEach(({assessment})=>inner.insertAdjacentHTML("beforeend",`<span class="full-event assessment">✓ ${escapeHTML(assessment.title)}</span>`));cell.onclick=()=>openDay(key);grid.appendChild(cell);}renderNotifications();}

  function notifications(){const items=[],today=dateKey(new Date()),end=new Date();end.setDate(end.getDate()+30);let unplanned=0;(user.terms||[]).forEach(term=>{for(let date=new Date(Math.max(parseDate(term.startDate),new Date()));date<=parseDate(term.endDate)&&date<=end;date.setDate(date.getDate()+1)){occurrences(dateKey(date)).filter(o=>o.block.blockType==="Instructional Time"&&!o.planned&&!lessonForOccurrence(o)).forEach(()=>unplanned++);}});if(unplanned)items.push({type:"danger",title:`${unplanned} instructional block${unplanned===1?"":"s"} need planning`,detail:"Next 30 days"});const pd=(user.calendarExceptions||[]).filter(e=>e.type==="PD Day"&&e.startDate>=today&&(!e.location||!e.description));if(pd.length)items.push({type:"info",title:`${pd.length} upcoming PD Day${pd.length===1?"":"s"} need details`,detail:"Location or description is incomplete"});const reflections=units().flatMap(unit=>(unit.lessons||[]).map(lesson=>({unit,lesson,plan:unit.workspace?.lessonPlans?.[lesson.id]}))).filter(x=>x.lesson.dateKey<today&&x.plan&&!x.plan.reflection?.completed);if(reflections.length)items.push({type:"warning",title:`${reflections.length} lesson reflection${reflections.length===1?"":"s"} unfinished`,detail:"Past lessons with reflection still open"});return items;}
  function renderNotifications(){const list=$("fullCalendarNotifications"),items=notifications();list.innerHTML=items.length?items.map(item=>`<article class="full-notification ${item.type}"><strong>${escapeHTML(item.title)}</strong><small>${escapeHTML(item.detail)}</small></article>`).join(""):'<div class="empty-state-card compact">Nothing urgent right now.</div>';}

  function dayAlerts(key){const alerts=[];if(exceptionFor(key))alerts.push(`${exceptionFor(key).type}: ${exceptionFor(key).label||exceptionFor(key).title||"Day off"}`);const need=occurrences(key).filter(o=>o.block.blockType==="Instructional Time"&&!o.planned&&!lessonForOccurrence(o)).length;if(need)alerts.push(`${need} instructional block${need===1?"":"s"} need planning.`);const weekStart=new Date(parseDate(key));weekStart.setDate(weekStart.getDate()-weekStart.getDay());const weekEnd=new Date(weekStart);weekEnd.setDate(weekEnd.getDate()+6);const weekly=notifications().map(i=>i.title);return{alerts,weekly};}
  function dailyHTML(key,print=false){const off=exceptionFor(key),rows=[];occurrences(key).filter(o=>matchingClass({grades:o.block.grades,subject:o.block.subject})).forEach(o=>{const linked=lessonForOccurrence(o),spec={grades:o.block.grades,subject:o.block.subject};if(o.block.blockType==="Instructional Time"){const colour=courseColour(spec);rows.push({time:o.block.startTime,html:`<article class="daily-event" style="--event-colour:${colour}"><time>${escapeHTML(fmtTime(o.block.startTime))}</time><div><strong>${escapeHTML(linked?lessonTitle(linked.lesson):(teachingClass(spec)?.name||classLabel(spec)))}</strong><span>${linked?escapeHTML(linked.unit.name):"Instructional Time · needs planning"}</span></div></article>`});}else rows.push({time:o.block.startTime,html:`<article class="daily-event noninstructional"><time>${escapeHTML(fmtTime(o.block.startTime))}</time><div><strong>${escapeHTML(o.block.label||o.block.blockType)}</strong><span>${escapeHTML(o.block.blockType)}</span></div></article>`});});tripsOn(key).filter(({unit})=>matchingClass(unit.classSpec)).forEach(({unit,trip})=>rows.push({time:"12:00",html:`<article class="daily-event" style="--event-colour:#ff9f43"><time>🚌</time><div><strong>Field Trip — ${escapeHTML(trip.title)}</strong><span>${escapeHTML(unit.name)}${trip.location?` · ${escapeHTML(trip.location)}`:""}</span></div></article>`}));assessmentsOn(key).filter(({unit})=>matchingClass(unit.classSpec)).forEach(({unit,assessment})=>rows.push({time:"23:30",html:`<article class="daily-event" style="--event-colour:#7a68df"><time>✓</time><div><strong>${escapeHTML(assessment.title)}</strong><span>${escapeHTML(assessment.type||"Assessment")} · ${escapeHTML(unit.name)}</span></div></article>`}));rows.sort((a,b)=>a.time.localeCompare(b.time));let html=off?`<div class="daily-day-off"><strong>${escapeHTML(off.label||off.title||off.type)}</strong><span>${escapeHTML(off.type)}${off.description?` · ${escapeHTML(off.description)}`:""}</span></div>`:"";html+=`<div class="daily-timeline">${rows.length?rows.map(r=>r.html).join(""):'<div class="empty-state-card">Nothing is scheduled for this date.</div>'}</div>`;if(print){const reflection=user.dailyRecords?.[key]?.reflection||"";html+=`<section class="print-daily-reflection"><h3>Daily Reflection</h3><div style="min-height:180px;border:1px solid #aaa;border-radius:10px;padding:12px">${reflection?escapeHTML(reflection).replaceAll("\n","<br>"):""}</div></section>`;}return html;}

  function saveState(){const keys=Object.keys(localStorage).filter(k=>/^teacherHQData_v\d+$/.test(k)).sort((a,b)=>Number(b.match(/\d+$/)[0])-Number(a.match(/\d+$/)[0]));if(keys[0])localStorage.setItem(keys[0],JSON.stringify(state));}
  function openDay(key){user.dailyRecords ||= {};user.dailyRecords[key] ||= {reflection:"",updatedAt:""};const dialog=$("fullDailyDialog"),alerts=dayAlerts(key);$("fullDailyTitle").textContent=fmtLong(key);$("fullDailyMeta").textContent="Daily timetable · instructional and non-instructional events";$("fullDailyAlerts").innerHTML=`${alerts.alerts.length?`<div class="daily-alert-block"><strong>For this day</strong>${alerts.alerts.map(a=>`<span>• ${escapeHTML(a)}</span>`).join("")}</div>`:""}${alerts.weekly.length?`<div class="daily-alert-block"><strong>This week / general</strong>${alerts.weekly.map(a=>`<span>• ${escapeHTML(a)}</span>`).join("")}</div>`:""}`;$("fullDailyContent").innerHTML=dailyHTML(key);const text=$("fullDailyReflection");text.value=user.dailyRecords[key].reflection||"";let timer;text.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{user.dailyRecords[key].reflection=text.value;user.dailyRecords[key].updatedAt=new Date().toISOString();saveState();$("fullDailySaved").textContent="Saved";},250);};$("fullDailyPrintView").onclick=()=>printDay(key,false);$("fullDailyDownload").onclick=()=>printDay(key,true);dialog.showModal();}
  function printDay(key,download){const html=`<!doctype html><html><head><meta charset="utf-8"><title>Teacher HQ — ${escapeHTML(fmtLong(key))}</title><style>@page{size:letter;margin:.55in}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17171a;font-size:12px}h1{margin-bottom:3px}.meta{color:#666;margin-bottom:18px}.daily-event{display:grid;grid-template-columns:90px 1fr;gap:10px;padding:8px;border-left:4px solid var(--event-colour,#777);margin:5px 0;background:#f8f8fa}.daily-event.noninstructional{font-size:10px;border-left-width:2px}.daily-event time{color:#666}.daily-event strong,.daily-event span{display:block}.daily-event span{color:#666}.daily-day-off{background:#eef6ff;padding:10px;border-radius:8px}.print-daily-reflection{margin-top:25px}.controls{margin-bottom:15px}@media print{.controls{display:none}}</style></head><body><div class="controls"><button onclick="window.print()">Print / Save PDF</button></div><h1>${escapeHTML(fmtLong(key))}</h1><div class="meta">${escapeHTML(user.username)} · Teacher HQ Daily Timetable</div>${dailyHTML(key,true)}</body></html>`;if(download){const blob=new Blob([html],{type:"text/html"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`TeacherHQ_Daily_${key}.html`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}else{const win=window.open("","_blank");if(!win)return alert("Allow pop-ups to open the print-friendly version.");win.document.write(html);win.document.close();}}

  function init(){load();if(!user){$("fullCalendarNoUser").classList.remove("hidden");return;}$("fullCalendarWorkspace").classList.remove("hidden");$("fullCalendarTitle").textContent=`${user.username}'s Calendar`;$("fullCalendarMeta").textContent=(user.terms||[]).length?`${user.terms.length} School Term${user.terms.length===1?"":"s"} · living schedule record`:"No School Terms yet";renderClasses();const now=new Date();visible=new Date(now.getFullYear(),now.getMonth(),1);$("fullCalendarPrev").onclick=()=>{visible=new Date(visible.getFullYear(),visible.getMonth()-1,1);render();};$("fullCalendarNext").onclick=()=>{visible=new Date(visible.getFullYear(),visible.getMonth()+1,1);render();};$("fullCalendarToday").onclick=()=>{const d=new Date();visible=new Date(d.getFullYear(),d.getMonth(),1);render();};$("fullDailyClose").onclick=()=>$("fullDailyDialog").close();render();}
  init();
})();
